services:
  mysql:
    image: mysql:8.0.3
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      TZ: America/Sao_Paulo
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy_network

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBIT_PORT}:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - proxy_network

  chat:
    build: .
    container_name: chatinho
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - proxy_network
    environment:
      - TZ=America/Sao_Paulo
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Sao_Paulo
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  mysql_data:
  rabbitmq_data:

networks:
  proxy_network:
    external: true